/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.as.server.api.accounts;

import com.as.server.dto.accounts.AccountDTO;
import com.as.server.dto.accounts.AccountRequest;
import com.as.server.dto.error.ApiError;
import com.as.server.entity.Account;
import com.as.server.util.ApiUtil;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.annotation.Generated;
import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-07T20:30:49.533631100+08:00[Asia/Shanghai]")
@Validated
@Tag(name = "Accounts", description = "the Accounts API")
public interface AccountsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /accounts : 创建顶级账户
     * 管理员创建新的顶级账户（银行、微信、支付宝等）。
     *
     * @param accountRequest  (optional)
     * @return 账户已创建 (status code 201)
     *         or 无效输入（名称重复或参数错误） (status code 400)
     *         or 权限不足（非管理员） (status code 403)
     */
    @Operation(
        operationId = "accountsCreate",
        summary = "创建顶级账户",
        tags = { "accounts" },
        responses = {
            @ApiResponse(responseCode = "201", description = "账户已创建", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Account.class))),
            @ApiResponse(responseCode = "400", description = "无效输入（名称重复或参数错误）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/accounts",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AccountDTO> accountsCreate(
        @Parameter(name = "AccountRequest", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) AccountRequest accountRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accountId\" : 0, \"name\" : \"name\", \"type\" : \"BANK\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /accounts/{accountId} : 删除顶级账户
     * 管理员删除指定账户，需确保无关联子账户。
     *
     * @param accountId 账户 ID (required)
     * @return 账户已删除 (status code 204)
     *         or 权限不足（非管理员） (status code 403)
     *         or 账户不存在 (status code 404)
     *         or 账户存在关联子账户，无法删除 (status code 409)
     */
    @Operation(
        operationId = "accountsDelete",
        summary = "删除顶级账户",
        tags = { "accounts" },
        responses = {
            @ApiResponse(responseCode = "204", description = "账户已删除"),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "404", description = "账户不存在", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "409", description = "账户存在关联子账户，无法删除", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/accounts/{accountId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Void> accountsDelete(
        @Parameter(name = "accountId", description = "账户 ID", required = true, schema = @Schema(description = "")) @PathVariable("accountId") Integer accountId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /accounts : 列出顶级账户
     * 管理员获取顶级账户列表。
     *
     * @return 账户列表 (status code 200)
     *         or 权限不足（非管理员） (status code 403)
     */
    @Operation(
        operationId = "accountsList",
        summary = "列出顶级账户",
        tags = { "accounts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "账户列表", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Account.class))),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/accounts",
        produces = { "application/json" }
    )
    default ResponseEntity<List<AccountDTO>> accountsList(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accountId\" : 0, \"name\" : \"name\", \"type\" : \"BANK\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /accounts/{accountId} : 更新顶级账户
     * 管理员更新指定账户的名称或类型。
     *
     * @param accountId 账户 ID (required)
     * @param accountRequest  (optional)
     * @return 账户已更新 (status code 200)
     *         or 无效输入（名称重复或参数错误） (status code 400)
     *         or 权限不足（非管理员） (status code 403)
     *         or 账户不存在 (status code 404)
     */
    @Operation(
        operationId = "accountsUpdate",
        summary = "更新顶级账户",
        tags = { "accounts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "账户已更新", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  Account.class))),
            @ApiResponse(responseCode = "400", description = "无效输入（名称重复或参数错误）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "404", description = "账户不存在", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/accounts/{accountId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AccountDTO> accountsUpdate(
        @Parameter(name = "accountId", description = "账户 ID", required = true, schema = @Schema(description = "")) @PathVariable("accountId") Integer accountId,
        @Parameter(name = "AccountRequest", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) AccountRequest accountRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accountId\" : 0, \"name\" : \"name\", \"type\" : \"BANK\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
