/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.as.server.api.users;

import com.as.server.dto.error.ApiError;
import com.as.server.dto.users.UserDTO;
import com.as.server.dto.users.UserRequest;
import com.as.server.util.ApiUtil;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import javax.annotation.Generated;
import javax.validation.Valid;
import java.util.List;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-07T20:30:49.533631100+08:00[Asia/Shanghai]")
@Validated
@Tag(name = "Users", description = "the Users API")
public interface UsersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /users : 创建用户
     * 管理员创建新用户，指定用户名、密码和角色（ADMIN 或 USER）。
     *
     * @param userRequest  (optional)
     * @return 用户已创建 (status code 201)
     *         or 无效输入（用户名重复或参数错误） (status code 400)
     *         or 权限不足（非管理员） (status code 403)
     */
    @Operation(
        operationId = "usersCreate",
        summary = "创建用户",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "201", description = "用户已创建", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  UserDTO.class))),
            @ApiResponse(responseCode = "400", description = "无效输入（用户名重复或参数错误）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/users",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<UserDTO> usersCreate(
        @Parameter(name = "UserRequest", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) UserRequest userRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"role\" : \"ADMIN\", \"id\" : 0, \"username\" : \"username\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /users/{userId} : 删除用户
     * 管理员删除指定用户，需确保用户无关联数据（如交易记录）。
     *
     * @param userId 用户 ID (required)
     * @return 用户已删除 (status code 204)
     *         or 权限不足（非管理员） (status code 403)
     *         or 用户不存在 (status code 404)
     *         or 用户存在关联数据（如交易记录），无法删除 (status code 409)
     */
    @Operation(
        operationId = "usersDelete",
        summary = "删除用户",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "204", description = "用户已删除"),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "404", description = "用户不存在", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "409", description = "用户存在关联数据（如交易记录），无法删除", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/users/{userId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Void> usersDelete(
        @Parameter(name = "userId", description = "用户 ID", required = true, schema = @Schema(description = "")) @PathVariable("userId") Integer userId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users : 列出用户
     * 管理员获取用户列表。
     *
     * @return 用户列表 (status code 200)
     *         or 权限不足（非管理员） (status code 403)
     */
    @Operation(
        operationId = "usersList",
        summary = "列出用户",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "用户列表", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  UserDTO.class))),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users",
        produces = { "application/json" }
    )
    default ResponseEntity<List<UserDTO>> usersList(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"role\" : \"ADMIN\", \"id\" : 0, \"username\" : \"username\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /users/{userId} : 更新用户
     * 管理员更新指定用户的信息（用户名、密码或角色）。
     *
     * @param userId 用户 ID (required)
     * @param userRequest  (optional)
     * @return 用户已更新 (status code 200)
     *         or 无效输入（用户名重复或参数错误） (status code 400)
     *         or 权限不足（非管理员） (status code 403)
     *         or 用户不存在 (status code 404)
     */
    @Operation(
        operationId = "usersUpdate",
        summary = "更新用户",
        tags = { "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "用户已更新", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  UserDTO.class))),
            @ApiResponse(responseCode = "400", description = "无效输入（用户名重复或参数错误）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "403", description = "权限不足（非管理员）", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class))),
            @ApiResponse(responseCode = "404", description = "用户不存在", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  ApiError.class)))
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/users/{userId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<UserDTO> usersUpdate(
        @Parameter(name = "userId", description = "用户 ID", required = true, schema = @Schema(description = "")) @PathVariable("userId") Integer userId,
        @Parameter(name = "UserRequest", description = "", schema = @Schema(description = "")) @Valid @RequestBody(required = false) UserRequest userRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"role\" : \"ADMIN\", \"id\" : 0, \"username\" : \"username\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
