/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * 家庭记账系统的 RESTful API，支持用户认证、人员管理、账户管理、交易记录和统计。 支持银行、微信、支付宝等多种账号，每种账号下可有多张卡或子账户。 角色权限： - 管理员：访问所有数据，管理用户、账号、子账户。 - 普通用户：仅访问通过 user_sub_accounts 关联的子账户和自己的交易/统计。 
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubAccount } from '../sub-accounts/sub-account';
// May contain unused imports in some cases
// @ts-ignore
import type { TransactionType } from '../transaction-type/transaction-type';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from '../user/user';

/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'transactionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'time'?: string;
    /**
     * 
     * @type {TransactionType}
     * @memberof Transaction
     */
    'transactionType'?: TransactionType;
    /**
     * 
     * @type {SubAccount}
     * @memberof Transaction
     */
    'subAccount'?: SubAccount;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'amount'?: number;
    /**
     * 
     * @type {User}
     * @memberof Transaction
     */
    'user'?: User;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'remarks'?: string;
}

