/* tslint:disable */
/* eslint-disable */
/**
 * 家庭记账系统 API
 * 家庭记账系统的 RESTful API，支持用户认证、人员管理、账户管理、交易记录和统计。 支持银行、微信、支付宝等多种账号，每种账号下可有多张卡或子账户。 角色权限： - 管理员：访问所有数据，管理用户、账号、子账户。 - 普通用户：仅访问通过 user_sub_accounts 关联的子账户和自己的交易/统计。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * JWT 令牌
     * @type {string}
     * @memberof LoginResponse
     */
    'token': string;
    /**
     * 用户角色
     * @type {string}
     * @memberof LoginResponse
     */
    'role': LoginResponseRoleEnum;
}

export const LoginResponseRoleEnum = {
    Admin: 'ADMIN',
    User: 'USER'
} as const;

export type LoginResponseRoleEnum = typeof LoginResponseRoleEnum[keyof typeof LoginResponseRoleEnum];


