/* tslint:disable */
/* eslint-disable */
/**
 * 家庭记账系统 API
 * 家庭记账系统的 RESTful API，支持用户认证、人员管理、账户管理、交易记录和统计。 支持银行、微信、支付宝等多种账号，每种账号下可有多张卡或子账户。 角色权限： - 管理员：访问所有数据，管理用户、账号、子账户。 - 普通用户：仅访问通过 user_sub_accounts 关联的子账户和自己的交易/统计。 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'transactionId': number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'time': string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'typeId': number;
    /**
     * 是否为收入（由typeId关联的transaction_types.is_income自动生成）
     * @type {boolean}
     * @memberof Transaction
     */
    'isIncome'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'subAccountId': number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'amount': string;
    /**
     * 
     * @type {number}
     * @memberof Transaction
     */
    'userId': number;
    /**
     * 
     * @type {string}
     * @memberof Transaction
     */
    'remarks'?: string;
}

